### PR TITLE
Cleaning up signup & login pages.

### PR DESCRIPTION
**Pull request by krues8dr**
#765

* Using email input type.
* Adding required attribute to required fields.
* Removing placeholders as these should not be used as labels.

@cmbirk @sethetter

### CODE REVIEW

**Comment by sethetter** [comment]
@krues8dr is it worth it to put in `*`'s next to the fields that are marked required? I realize this is all of them, but it's somewhat of an "expected" interface feature most places.

**Comment by krues8dr** [comment]
@sethetter Probably, but maybe add that to #748 instead of here?

**Comment by krues8dr** [comment]
Instead of `*` I actually like having the word `required` present, personally.  I think I've done this on other forms of ours...

**Comment by sethetter** [comment]
Seems reasonable to me. Otherwise everything looks good! I'll merge.

**Pull request merged**
