### PR TITLE
Merge from dev, several small fixes

### PR DESCRIPTION
**Pull request by krues8dr**
I've merged in everything from dev up to (but not including) the laravel upgrade, which should be stable.  I've then applied fixes for #688 #689 and #690.  @sethetter @cmbirk how does this look? I should have split this into two different PRs probably.

### CODE REVIEW

**Comment by sethetter** [comment]
@krues8dr Not sure if you wanted to get this one in or not, #683, it's fixed and waiting for merge. The issue was broken like/flag actions on annotation comments.

**Comment by cmbirk** [comment]
@krues8dr I just created a local instance from your fork.  I'm not getting the right side on the document editor page ( the markdown rendered as a preview )

**Comment by krues8dr** [comment]
@cmbirk That's not there on live either.  I don't even remember that being there in recent history.

@sethetter I'll see if it's an easy cherrypick in a bit.

**Comment by sethetter** [comment]
@krues8dr cool, it should be.

**Comment by krues8dr** [comment]
@cmbirk That should do the trick: 23fa8898c75ad0e96ccc31c923b06d874d0d420f

**Comment by krues8dr** [comment]
:+1:

**Pull request merged**
