### PR TITLE
Issue 712 - Fix normalizing of sponsor data

### PR DESCRIPTION
**Pull request by sethetter**
When we populate from the DB we have to wait until after the query can be
fetched to noramlize and populate the sponsor data on individual documents to
always have a `display_name`. This was only affecting docs with user sponsors.

Also updated some variables to be pluralized where it makes sense (for `hasMany`
relationships).

Issue #712 

@cmbirk @krues8dr

### CODE REVIEW

**Comment by cmbirk** [comment]
Looking like there's some timeout errors here.  I restarted the build and we'll see what happens

**Comment by sethetter** [comment]
@cmbirk @krues8dr, tests should be passing, check whenever you're ready.

**Comment by sethetter** [comment]
Not sure why one of the builds is failing. It's happening pretty inconsistently though :( Everything should be good.

**Comment by sethetter** [comment]
@cmbirk @krues8dr tests passing now. Care to check/merge?

**Pull request merged**
