### PR TITLE
Issue 923 - Allow overwriting of settings in locale files

### PR DESCRIPTION
**Pull request by sethetter**
Also updated the README with instructions on customizing Madison through styling
and language.

Issue #923 

@krues8dr

### CODE REVIEW

**Comment by sethetter** [comment]
Ran into an issue with the page title not being translated before it sets the title.

This is a result of using `$translate.instant('key')` instead of `$translate('key').then(function(translation) {})`. If we use the latter, it makes sure the translation is loaded before setting the page title.

I've also found that if we use `<title ng-bind="page.title()">` instead of `<title>{{ page.title() }}</title>`, it will mask the interpolation and we won't get that flash of the page title being set as the translation key.

@krues8dr this might be outside the scope of this issue. Should we call this one good and I'll open another issue to tackle this real quick?

**Comment by krues8dr** [comment]
Yeah, a new issue is good.  FWIW, I ran into an issue using bind that way on the title that I'm trying to remember, something about not having access ot the main site title when the page is first loaded maybe?  It's been a long time.

**Comment by sethetter** [comment]
@krues8dr yeah I thought about that, but remembered you had fixed the social sharing issue in another ticket, so that shouldn't be a problem here.

However, that approach will need revisiting with 3.0, since requests won't be getting served from the Laravel app anymore >_<

**Comment by sethetter** [comment]
Alright, I've created #930 and will start that work there. If you want to review this and merge when you get a chance that'd be great. I'll start #930 forked from this branch.

**Comment by barryvdh** [comment]
So override the local style works, but the _custom stylesheets are loaded first, right? This is needed to make sure the variables are set first, but this will load all styles *after* the custom styles, so you need to suffix everything with `!important` if you want to change something. Is that intended?

**Comment by barryvdh** [comment]
About the style, imho it would make more sense to do something like this:

`@import 'custom/settings -> include after the bootstrap/madison settings (where `@import 'custom/settings';` now is placed).

`@import 'custom'` as the final stylesheet import in style.scss, to allow easy overrides in css styles.

**Comment by krues8dr** [comment]
@barryvdh The problem I ran into with that is that since we're using SASS, frequently I wanted to just override a color or particular text treatment.  Since SASS doesn't do late-evaluation, it's way easier to do that by overriding the variable early, than having to manually override every single case where the color is used.  

However, if you want to override a particular style, you can wrap your style with the `.madison` class which is on the `body`, as that will add an extra level of specificity and we will never use it ourselves.

You can read more about this in the [theming section](https://github.com/opengovfoundation/madison/tree/master/docs#theming) of the docs, and see how it's used [in the DC instance](https://github.com/DCgov/dc-madison/blob/master/public/sass/custom/_dc.scss).

Let me know if this doesn't make sense.

**Pull request merged**
