### PR TITLE
Issue 786

### PR DESCRIPTION
**Pull request by krues8dr**
@cmbirk @sethetter per our conversation this morning, just hiding annotations altogether at first.  Also hiding the Table of Contents.

### CODE REVIEW

**Comment by sethetter** [comment]
Only thing I see that we might want to address is that the "Discussion" tab doesn't take up the full page width like the Bill Text tab does. Otherwise :+1:!

**Comment by krues8dr** [comment]
@sethetter  yup, this ticket doesn't address that though.  Still lots of things to do here.

**Comment by sethetter** [comment]
Ah right, another item in the issue I see.

Cool, well this looks good to merge to me! There are conflicts but it's all in build assets. I'll take care of these and handle the merge.

**Comment by krues8dr** [comment]
Many thanks!

**Comment by krues8dr** [comment]
(I did not mean to click the Restore button.  Disregard.)

**Pull request merged**
