### PR TITLE
Issue 786

### PR DESCRIPTION
**Pull request by krues8dr**
This gives us back the annotation pane on mobile per #786

### CODE REVIEW

**Comment by krues8dr** [comment]
@sethetter @cmbirk

**Comment by cmbirk** [comment]
typo in the locales file for `info.message.mobilebrowser.annotate`:

`Please use a desktop ot laptop computer`

**Comment by krues8dr** [comment]
_sigh_

**Comment by krues8dr** [comment]
:arrow_left::coffee:

@cmbirk how 'bout now?

**Comment by cmbirk** [comment]
Looks good.  Only thing we might want to refine is the language.  We should probably mention _why_ it's required.  Something like "We're currently working on the ability to annotate on mobile browsers, but until then please open on a desktop to annotate."

**Comment by krues8dr** [comment]
:+1:

**Pull request merged**
